name: User Audit
on:
  workflow_dispatch:
jobs:
  logRepoPermissions:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/graphql-action@v2.x
        id: repo_permission_audit
        with:
          query: |
            query repo_permissions($owner: String!, $repo: String!, $affiliation: CollaboratorAffiliation!, $endCursor: String) {
              repository(owner: $owner, name: $repo) {
               nameWithOwner
                collaborators(first: 100, affiliation: $affiliation, after: $endCursor) {
                    pageInfo {
                      endCursor
                      hasNextPage
                    }
                    edges {
                      permission
                      node {
                        isEmployee
                        login
                        name
                      }
                    }
                  }
                }
              }
          owner: ${{ vars.OWNER }}
          repo: ${{ vars.REPO}}
          affiliation: 'ALL'
        env:
          GITHUB_TOKEN: ${{ secrets.OCTODEMO_REPO_AUDIT }}
  writeCsv:
    needs: logRepoPermissions
    runs-on: ubuntu-latest
    steps:
      - name: Write to CSV file
        uses: gr2m/write-csv-file-action@v1.0.0

        with:
          path: data/repo-permission.csv
          columns: repo, user, permission
          "repo": ${{ fromJson(steps.logRepoPermissions.outputs.data).repository.nameWithOwner }}
          "user": ${{ fromJson(steps.logRepoPermissions.outputs.data).repository.collaborators.edges.node.login }}
          "permission": ${{ fromJson(steps.logRepoPermissions.outputs.data).repository.collaborators.edges.permission }}
