name: User Audit action
on:
  workflow_dispatch:
jobs:
   Repo-Permissions:
    runs-on: ubuntu-latest
    steps:
      - uses: gh-customer-success/user-audit@7cc1c6a1f76a8529f5f8d65b1207bd546ad6891b
        with:
          api-token: ${{ secrets.GITHUB_TOKEN }}
          org: ${{ github.repository_owner }}
          repo: ${{vars.repo}}
       