name: User Audit action
on:
  workflow_dispatch:
jobs:
   Repo-Permissions:
    runs-on: ubuntu-latest
    steps:
      - uses: gh-customer-success/user-audit@9b262550bc1689d86da59a38f0896bcef7f75a57
        with:
          api_token: ${{ secrets.OCTODEMO_REPO_AUDIT }}
          owner: ${{ github.repository_owner }}
          repo: ${{vars.repo}}
