name: User Audit action
on:
  workflow_dispatch:
jobs:
   Repo-Permissions:
    runs-on: ubuntu-latest
    steps:
      -
        name: run audit
        uses: gh-customer-success/user-audit@1cf01977092d54f50833ddfe7a756a7a9a6e7ec6
        with:
          api_token: ${{ secrets.OCTODEMO_REPO_AUDIT }}
          owner: ${{ vars.OWNER }}
          repo: ${{vars.repo}}
        id: audit
      -
        name: print output
        run: echo "${{steps.audit.outputs.response}}"
