name: User Audit action
on:
  workflow_dispatch:
jobs:
   Repo-Permissions:
    runs-on: ubuntu-latest
    steps:
      -
        name: run audit
        uses: gh-customer-success/user-audit@5f9bd80d5860642103571ed297dacd4693d00a33
        with:
          api_token: ${{ secrets.OCTODEMO_REPO_AUDIT }}
          owner: ${{ vars.OWNER }}
          repo: ${{vars.repo}}
        id: audit
      -
        name: print output
        run: |
          echo "TEAMS ${{steps.audit.outputs.teams}}"
          echo "REPOS ${{steps.audit.outputs.repos}}"
