name: User Audit action
on:
  workflow_dispatch:
jobs:
   Repo-Permissions:
    runs-on: ubuntu-latest
    steps:
      - uses: gh-customer-success/user-audit@latest
        with:
          api-token: ${{ secrets.GITHUB_TOKEN }}
          org: ${{ github.repository_owner }}
          repo: ${{vars.repo}}
       
