name: User Audit action
on:
  workflow_dispatch:
jobs:
   Repo-Permissions:
    runs-on: ubuntu-latest
    steps:
      - uses: gh-customer-success/github-user-audit@main
        with:
          api_token: ${{ secrets.USER_AUDIT}}
          owner: ${{ github.repository_owner }}
        id: audit
       
