name: User Audit
on:
  workflow_dispatch:
jobs:
  logRepoPermissions:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/graphql-action@v2.x
        id: repo_permission_audit
        with:
          query: |
            query ($owner: String!, $repo: String!, $affiliation: CollaboratorAffiliation!, $endCursor: String) {
            repository(owner: $owner, name: $repo) {
             nameWithOwner
            collaborators(first: 100, affiliation: $affiliation, after: $endCursor) {
                pageInfo {
                  endCursor
                  hasNextPage
                }
                edges {
                  permission
                  node {
                    isEmployee
                    login
                    name
                  }
                }
              }
            }

          owner: ${{ vars.OWNER }}
          repo: ${{ vars.REPO}}
          affiliation: 'ALL'
        env:
          GITHUB_TOKEN: ${{ secrets.OCTODEMO_REPO_AUDIT }}
      - run: "echo 'latest permissions: ${{ steps.repo_permission_audit.outputs.data }}'"
